### ISSUE TITLE
Add support for HttpContent

### ISSUE THREAD

**Issue by flcdrg** [VerifyTests/Verify.AspNetCore#2]
#### Is the feature request related to a problem

I want to write tests that compare the content of `HttpContent` (eg. as found in [Content](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.content?view=net-6.0#System_Net_Http_HttpRequestMessage_Content) property of [HttpRequestMessage](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage?view=net-6.0#properties))

#### Describe the solution

Add a converter `HttpContentConverter`

#### Describe alternatives considered

I could extract the value directly via `await content.ReadAsStringAsync()` but then you would lose the context from the parent `HttpRequestMessage` object

**Comment by SimonCropp** [comment]
can you use the httpcontent converter in https://github.com/VerifyTests/Verify.Http?

**Comment by flcdrg** [comment]
ah, why yes! Didn't realise it might be somewhere else!

**Comment by daniatic** [comment]
@SimonCropp I was wondering how these two extension (AspNetCore and Http) differ? I was using the AspNetCore one until I realized that it didnt not serialize the HttpContent, thats when I stumbled upon this issue and found out about Verify.Http. First I tried to stick with Verify.AspNetCore and only use the HttpContentConverter from Verify.Http which I could not access due to its internal access modifier. Then I switched all the way to Verify.Http. It serialization outputs are very similar but seam to fulfill different purposes, which I haven't yet invested time to investigate. Could you please very briefly explain the differences and the purpose of each library?

My Context: I'm working on a asp.net core controller based webapi which I test by using WebApplicationFactory and its provided HttpClient. The responses of it I just feed into Verify.
